### ISSUE TITLE
What is Orienteering page

### ISSUE THREAD

**Issue by fbaygul** [YTU-orienteering/YTU_orienteering-app#12]

**Comment by fbaygul** [comment]
IOG tarzı bir oryantiring nedir ve genel bilgiler bulunan bir sayfa yapılması.

**Comment by fbaygul** [comment]
Bu sayfadaki veriler değişmeyeceği için uygulama içine gömülecek.

**Comment by fbaygul** [comment]
@MustafaBayrakk @furkanerytu 
Ana oryantring sayfası ve alt sayfalar oluşturuldu. Buradan herkes istediği sayfayı alıp yapabilir yada bölüşebiliriz . Temel kod hazır.

**Comment by MustafaBayrakk** [comment]
Kontrol Tanımları ve Kontrol Tanımları-Örnekler tablarını alıyorum ilk olarak fyi :) @fbaygul @furkanerytu

**Comment by fbaygul** [comment]
pusula kullanımı ve bağlantılar sayfasınıda ben alıyorum.

**Comment by fbaygul** [comment]
Disk Önbelleği (Disk Cache): Bu tür önbellek, verileri cihazın depolama birimine (genellikle sabit disk veya flaş bellek) kaydederek saklar. Bu sayede uygulama, aynı verilere tekrar erişim gerektiğinde veritabanından veya ağdan çekmek yerine yerel depolamadan hızlı bir şekilde erişebilir. Ancak disk önbelleği, depolama birimine erişim maliyeti nedeniyle diğer önbellek türlerine göre daha yavaş olabilir.

RAM Önbelleği (RAM Cache): RAM önbelleği, verileri cihazın RAM'ine kaydederek hızlı erişim sağlar. RAM, disk depolamadan daha hızlıdır, bu nedenle RAM önbelleği genellikle daha hızlı çalışır. Ancak, RAM sınırlı bir kaynaktır, bu nedenle büyük miktarda veri için uygun olmayabilir.

Ağ Önbelleği (Network Cache): Ağ önbelleği, önceden çekilmiş verileri ağ üzerinden alarak hızlı erişim sağlar. Örneğin, bir web tarayıcısı, daha önce ziyaret edilen bir web sayfasını ağ önbelleği sayesinde tekrar indirmek yerine yerelde saklayabilir. Bu, sayfanın daha hızlı yüklenmesini sağlar.

Özel Önbellek (Custom Cache): Bazı uygulamalar, belirli kullanım senaryolarına uygun olarak özel önbellek türleri kullanabilir. Örneğin, bir resim düzenleme uygulaması, kullanıcının daha önce işlemiş olduğu resimleri hızlı bir şekilde görüntülemek için özel bir önbellek mekanizması kullanabilir.
